import { describe, expect, it } from "vitest";
import type { CompatibilityStatus, EcosystemComponent, EcosystemData } from "@/lib/domain/types";
import { diagnoseRecommendations, estimateModelFit, hardwareProfileSchema, recommendStacks, runtimeHardwareFit, type RecommendationInput } from "./index";
const profile = hardwareProfileSchema.parse({ name: "Mac", operatingSystem: "macOS", architecture: "apple_silicon", memoryGb: 32, gpuType: "apple", appleChip: "M3" });
describe("recommendation memory estimates", () => {
 it("estimates dense 7B 4-bit conservatively", () => expect(estimateModelFit({ modelMetadata: { parameterCount: 7e9 } } as never, profile).estimatedModelGb).toBeCloseTo(3.5, 1));
 it("uses total rather than active MoE parameters", () => expect(estimateModelFit({ modelMetadata: { parameterCount: 70e9, activeParameterCount: 8e9 } } as never, profile).estimatedModelGb).toBeGreaterThan(30));
 it("marks missing metadata unknown", () => expect(estimateModelFit({} as never, profile).level).toBe("unknown"));
 it("distinguishes CUDA and CPU-only runtime support", () => {
   const cuda = hardwareProfileSchema.parse({ name:"GPU", operatingSystem:"Linux", architecture:"x64", memoryGb:64,gpuType:"nvidia",vramGb:24,cudaAvailable:true });
   const cpu = hardwareProfileSchema.parse({ name:"CPU", operatingSystem:"Linux", architecture:"x64", memoryGb:32,gpuType:"none",cpuOnly:true });
   expect(runtimeHardwareFit({ tags:["runtime","CUDA"], operatingSystems:["Linux"] } as never,cuda)).toBe("supported");
   expect(runtimeHardwareFit({ tags:["runtime","CUDA"], operatingSystems:["Linux"] } as never,cpu)).toBe("incompatible");
 });
});

const baseInput = (overrides: Partial<RecommendationInput> = {}): RecommendationInput => ({ task: "assistant", runPreference: "hybrid", interface: "any", priorities: [], verifiedOnly: false, profile: hardwareProfileSchema.parse({ name: "Linux", operatingSystem: "Linux", architecture: "x64", memoryGb: 64, gpuType: "none", cpuOnly: true }), ...overrides });
const component = (id: string, componentType: EcosystemComponent["componentType"], overrides: Partial<EcosystemComponent> = {}): EcosystemComponent => ({ id, slug: id, name: id, shortName: id, componentType, description: id, status: "published", localCapable: true, operatingSystems: ["Linux", "macOS"], tags: [], ...overrides });
type RouteSpec = { id: string; model?: Partial<EcosystemComponent>; runtime?: Partial<EcosystemComponent>; agent?: Partial<EcosystemComponent>; status?: CompatibilityStatus; direct?: boolean };
function fixture(routes: RouteSpec[]): EcosystemData {
 const components: EcosystemComponent[]=[]; const ports: EcosystemData["ports"]=[]; const compatibilityEdges: EcosystemData["compatibilityEdges"]=[];
 for(const route of routes){const model=component(`${route.id}-model`, "model", {modelMetadata:{parameterCount:7e9,modalities:[]},...route.model}); const agent=component(`${route.id}-agent`,"agent",route.agent); const chain=route.direct?[model,agent]:[model,component(`${route.id}-runtime`,"runtime",route.runtime),agent]; components.push(...chain); chain.forEach((item,index)=>{ports.push({id:`${item.id}-out`,componentId:item.id,name:"out",slug:"out",direction:"output",protocolType:"test",transportType:"test",dataType:"test",cardinality:"many",required:false,description:""},{id:`${item.id}-in`,componentId:item.id,name:"in",slug:"in",direction:"input",protocolType:"test",transportType:"test",dataType:"test",cardinality:"many",required:false,description:""});if(index)compatibilityEdges.push({id:`${route.id}-edge-${index}`,sourcePortId:`${chain[index-1].id}-out`,targetPortId:`${item.id}-in`,status:route.status??"verified_official",compatibilityLevel:"native",confidence:1,notes:"fixture",platformConstraints:[],configurationRequired:false,sourceIds:["fixture"]});});}
 return {components,ports,compatibilityEdges,sources:[],dataSource:{mode:"bootstrap",label:"test"}};
}
const names=(data:EcosystemData,input:RecommendationInput)=>recommendStacks(data,input).map(result=>data.components.find(item=>item.id===result.path.componentIds[0])!.shortName);

describe("recommendation ranking matrix",()=>{
 it("accepts supported CUDA and rejects unsupported or unknown strict CUDA runtimes",()=>{const data=fixture([{id:"cuda",runtime:{tags:["cuda"]}},{id:"unknown",runtime:{tags:[]}},{id:"apple",runtime:{tags:["apple silicon"]}}]);const input=baseInput({priorities:["cuda"],profile:hardwareProfileSchema.parse({name:"GPU",operatingSystem:"Linux",architecture:"x64",memoryGb:64,gpuType:"nvidia",vramGb:24,cudaAvailable:true})});expect(names(data,input)).toEqual(["cuda-model"]);});
 it("keeps a lower-ranked CUDA path when the top path for the same model is not CUDA-capable",()=>{const data=fixture([{id:"qwen",runtime:{tags:[]}}]);const model=data.components.find(item=>item.id==="qwen-model")!;const agent=data.components.find(item=>item.id==="qwen-agent")!;const runtime=component("llama-cpp","runtime",{tags:["cuda"]});data.components.push(runtime);data.ports.push({id:"llama-cpp-in",componentId:runtime.id,name:"in",slug:"in",direction:"input",protocolType:"test",transportType:"test",dataType:"test",cardinality:"many",required:false,description:""},{id:"llama-cpp-out",componentId:runtime.id,name:"out",slug:"out",direction:"output",protocolType:"test",transportType:"test",dataType:"test",cardinality:"many",required:false,description:""});data.compatibilityEdges.push({id:"qwen-to-llama",sourcePortId:`${model.id}-out`,targetPortId:"llama-cpp-in",status:"verified_first_party",compatibilityLevel:"compatible",confidence:.9,notes:"fixture",platformConstraints:[],configurationRequired:false,sourceIds:["fixture"]},{id:"llama-to-hermes",sourcePortId:"llama-cpp-out",targetPortId:`${agent.id}-in`,status:"verified_first_party",compatibilityLevel:"compatible",confidence:.9,notes:"fixture",platformConstraints:[],configurationRequired:false,sourceIds:["fixture"]});const input=baseInput({priorities:["cuda"],profile:hardwareProfileSchema.parse({name:"GPU",operatingSystem:"Linux",architecture:"x64",memoryGb:64,gpuType:"nvidia",vramGb:24,cudaAvailable:true})});expect(recommendStacks(data,input).map(result=>result.path.componentIds)).toContainEqual([model.id,runtime.id,agent.id]);});
 it("uses VRAM to reject oversized strict-CUDA candidates and broaden feasible choices",()=>{const data=fixture([{id:"small",runtime:{tags:["cuda"]}},{id:"large",runtime:{tags:["cuda"]},model:{modelMetadata:{parameterCount:30e9,modalities:[]}}}]);const gpu=(vramGb:number)=>baseInput({priorities:["cuda"],profile:hardwareProfileSchema.parse({name:"GPU",operatingSystem:"Linux",architecture:"x64",memoryGb:64,gpuType:"nvidia",vramGb,cudaAvailable:true})});expect(names(data,gpu(16))).toEqual(["small-model"]);expect(names(data,gpu(64))).toEqual(expect.arrayContaining(["small-model","large-model"]));});
 it("excludes CUDA-only CPU routes and ranks the practical CPU model first",()=>{const data=fixture([{id:"cuda",runtime:{tags:["cuda"]}},{id:"small",runtime:{tags:[]}},{id:"large",runtime:{tags:[]},model:{modelMetadata:{parameterCount:30e9,modalities:[]}}}]);expect(names(data,baseInput())[0]).toBe("small-model");expect(names(data,baseInput())).not.toContain("cuda-model");});
 it("keeps Apple behavior distinct from CUDA behavior",()=>{const data=fixture([{id:"cuda",runtime:{tags:["cuda"]}},{id:"mac",runtime:{operatingSystems:["macOS"]}}]);expect(names(data,baseInput({profile:hardwareProfileSchema.parse({name:"Mac",operatingSystem:"macOS",architecture:"apple_silicon",memoryGb:32,gpuType:"apple",appleChip:"M3"})}))).toEqual(["mac-model"]);});
 it("ranks known fit and verified active routes above unknown, lower-trust, deprecated equivalents",()=>{const data=fixture([{id:"known",runtime:{}},{id:"unknown",runtime:{},model:{modelMetadata:undefined}},{id:"community",runtime:{},status:"verified_community"},{id:"old",runtime:{},model:{status:"deprecated"}}]);const ranked=names(data,baseInput());expect(ranked.indexOf("known-model")).toBeLessThan(ranked.indexOf("unknown-model"));expect(ranked.indexOf("known-model")).toBeLessThan(ranked.indexOf("community-model"));expect(ranked).not.toContain("old-model");});
 it("deduplicates equivalent stacks and applies CLI, GUI, privacy, and easy setup preferences",()=>{const data=fixture([{id:"cli",direct:true,agent:{cliAvailable:true,guiAvailable:false}},{id:"gui",direct:true,agent:{cliAvailable:false,guiAvailable:true}},{id:"cloud",direct:true,model:{localCapable:false},agent:{localCapable:false}}]);data.compatibilityEdges.push({...data.compatibilityEdges[0],id:"duplicate-edge"});expect(names(data,baseInput({interface:"cli"}))[0]).toBe("cli-model");expect(names(data,baseInput({interface:"gui"}))[0]).toBe("gui-model");expect(names(data,baseInput({priorities:["privacy"]}))[0]).not.toBe("cloud-model");expect(recommendStacks(data,baseInput()).filter(result=>result.path.componentIds[0]==="cli-model")).toHaveLength(1);const plain=recommendStacks(data,baseInput()).find(result=>result.path.componentIds[0]==="cli-model")!;const easy=recommendStacks(data,baseInput({priorities:["easy_setup"]})).find(result=>result.path.componentIds[0]==="cli-model")!;expect(easy.score).toBeGreaterThan(plain.score);});
 it("prefers fewer hops when other factors are equivalent",()=>expect(names(fixture([{id:"short",direct:true},{id:"long"}]),baseInput())[0]).toBe("short-model"));
});

describe("no-route diagnostics",()=>{
 it("returns structured CUDA and local-memory reasons with explicit relaxations",()=>{const data=fixture([{id:"big",runtime:{tags:["cuda"]},model:{modelMetadata:{parameterCount:70e9,modalities:[]}}}]);const result=diagnoseRecommendations(data,baseInput({runPreference:"local",priorities:["cuda"],profile:hardwareProfileSchema.parse({name:"Tiny GPU",operatingSystem:"Linux",architecture:"x64",memoryGb:16,gpuType:"nvidia",vramGb:8,cudaAvailable:true})}));expect(result.recommendations).toEqual([]);expect(result.blockers.map(item=>item.code)).toEqual(expect.arrayContaining(["strict_cuda_no_viable_route","insufficient_local_memory"]));expect(result.relaxations.map(item=>item.code)).toEqual(expect.arrayContaining(["disable_strict_cuda","increase_memory","allow_cloud"]));});
 it("reports verified-only where only lower-trust routes exist",()=>{const result=diagnoseRecommendations(fixture([{id:"community",runtime:{},status:"verified_community"}]),baseInput({verifiedOnly:true}));expect(result.blockers.map(item=>item.code)).toContain("verified_only_no_viable_route");expect(result.relaxations.map(item=>item.code)).toContain("allow_lower_trust");});
 it("reports a task constraint with no compatible vision candidate",()=>{const result=diagnoseRecommendations(fixture([{id:"text",runtime:{}}]),baseInput({task:"vision"}));expect(result.blockers.map(item=>item.code)).toContain("task_has_no_compatible_candidate");expect(result.relaxations.map(item=>item.code)).toContain("choose_supported_task");});
});
