"use client";

import { useState } from "react";
import { bulkReview } from "../actions";

export type BulkProposal = { id:string; component:string; field:string|null; risk:string; authority:string; createdAt:string };

export function BulkReviewClient({ proposals }: { proposals: BulkProposal[] }) {
  const [selected,setSelected]=useState<string[]>([]); const [confirmation,setConfirmation]=useState<"approve"|"reject"|null>(null);
  const chosen=proposals.filter(item=>selected.includes(item.id)); const blocked=chosen.filter(item=>item.risk==="high");
  const risks=Object.entries(chosen.reduce<Record<string,number>>((all,item)=>({ ...all,[item.risk]:(all[item.risk]??0)+1}),{})); const fields=[...new Set(chosen.map(item=>item.field??"operation"))]; const components=new Set(chosen.map(item=>item.component)).size;
  function toggle(id:string){setSelected(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);setConfirmation(null);}
  return <form action={bulkReview} onSubmit={(event)=>{ if(!confirmation){event.preventDefault();} }}><p className="muted">Bulk approval is server-enforced for objective, supported proposals only.</p><div className="proposal-list">{proposals.map(item=><label className="proposal-row" key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/>{selected.includes(item.id)&&<input type="hidden" name="proposalId" value={item.id}/>}<span><strong>{item.component}</strong><span>{item.field} · {item.risk} · {item.authority}</span></span><small>{new Date(item.createdAt).toLocaleString()}</small></label>)}</div>{selected.length>0&&<section className="bulk-summary"><strong>{selected.length} selected · {components} components</strong><span>Risk: {risks.map(([risk,count])=>`${risk} ${count}`).join(", ")}</span><span>Fields: {fields.join(", ")}</span>{blocked.length>0&&<p className="form-error">Approval disabled: {blocked.length} high-risk or review-required proposal{blocked.length===1?"":"s"} selected.</p>}<div className="review-actions"><button type="button" className="button secondary" onClick={()=>{setSelected([]);setConfirmation(null);}}>Clear selection</button><button type="button" className="button primary" disabled={blocked.length>0} onClick={()=>setConfirmation("approve")}>Approve selected</button><button type="button" className="button secondary" onClick={()=>setConfirmation("reject")}>Reject selected</button></div>{confirmation&&<div className="trust-card verified"><span><strong>{confirmation==="approve"?`Approve ${selected.length} selected proposals?`:`Reject ${selected.length} selected proposals?`}</strong><small>{confirmation==="approve"?"This applies only the eligible objective changes shown above.":"Rejected proposals remain in immutable audit history."}</small></span><button className="button primary" name="decision" value={confirmation}>Confirm {confirmation}</button><button className="button secondary" type="button" onClick={()=>setConfirmation(null)}>Cancel</button></div>}</section>}{!proposals.length&&<p className="empty-copy">No proposals match these filters.</p>}</form>;
}
