import Link from "next/link";
import { Clock3, LockKeyhole, ShieldCheck } from "lucide-react";
import { rerunUpdater, reviewProposal } from "./actions";
import { SignOutButton } from "./sign-out-button";
import { getEcosystemData } from "@/lib/data/ecosystem-repository";
import { getAdminUpdateCenter } from "@/lib/updater/admin-repository";
import { getCurrentAuthorization } from "@/lib/auth/authorization";

export const metadata = { title: "Admin · AI Patchbay" };

export default async function AdminPage() {
  const [{ dataSource }, authorization] = await Promise.all([getEcosystemData(), getCurrentAuthorization()]);
  const canReview = authorization.role === "editor" || authorization.role === "admin";
  const center = canReview ? await getAdminUpdateCenter(authorization.supabase) : null;
  if (!canReview) return <main className="admin-page"><section className="admin-lock"><span className="monogram large"><LockKeyhole size={24}/></span><span className="eyebrow">Protected editor</span><h1>Authentication required</h1><p>{authorization.user ? "Your account has no editor role. Ask an administrator to provision access." : "Editorial access requires an authenticated editor or admin account."}</p><p className="muted" data-testid="data-source">Data source: {dataSource.label}</p>{!authorization.user && <Link className="button primary" href="/login?next=/admin">Sign in</Link>}</section></main>;
  return <main className="admin-page"><section className="admin-lock"><span className="monogram large"><ShieldCheck size={24}/></span><span className="eyebrow">Protected editor</span><h1>Update Center</h1><p>External observations become reviewable proposals before they affect curated records.</p><form action={rerunUpdater} className="run-controls"><button className="button secondary" name="adapter" value="all">Run all</button><button className="button secondary" name="adapter" value="github">GitHub</button><button className="button secondary" name="adapter" value="huggingface">Hugging Face</button><button className="button secondary" name="adapter" value="openrouter">OpenRouter</button></form></section><section className="admin-preview update-center"><div className="admin-user"><span><span className="eyebrow">Signed in</span><strong>{authorization.displayName ?? authorization.user?.email ?? "Editor"}</strong><small>{authorization.role}</small></span><SignOutButton/></div><nav className="admin-tabs"><Link href="/admin">Overview</Link><Link href="/admin/proposals">Proposals</Link><Link href="/admin/compatibility">Compatibility</Link><Link href="/admin/evidence">Evidence</Link></nav><div className="update-stats"><span><strong>{center!.proposals.filter(item=>item.change_status==="pending").length}</strong> pending</span><span><strong>{center!.staleComponents.length}</strong> stale</span><span><strong>{center!.proposals.filter(item=>item.change_status==="auto_applied").length}</strong> auto-applied</span></div><div className="section-heading"><span>Recent updater runs</span></div>{center!.runs.slice(0,8).map(run=><Link className="admin-module" key={run.id} href={`/admin/runs/${run.id}`}><strong>{run.adapter_id}</strong><span>{run.status} · {run.proposals_created} proposals{run.error_count ? ` · ${run.error_count} errors` : ""}</span><Clock3 size={15}/></Link>)}<div className="section-heading"><span>Pending review</span><Link href="/admin/proposals">View all</Link></div>{center!.proposals.filter(item=>item.change_status==="pending").slice(0,8).map(proposal=><article className="proposal-card" key={proposal.id}><div><strong>{proposal.component?.name ?? "Unmapped component"}</strong><small>{proposal.field_name} · {proposal.risk_classification} risk · {proposal.source_authority}</small><p>{proposal.rationale}</p><Link className="detail-link" href={`/admin/proposals/${proposal.id}`}>Open detail</Link></div><form action={reviewProposal}><input type="hidden" name="proposalId" value={proposal.id}/><button className="button primary" name="decision" value="approve">Approve</button><button className="button secondary" name="decision" value="reject">Reject</button></form></article>)}</section></main>;
}
